# Generated by Django 4.2.11 on 2024-04-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
