# Generated by Django 4.2.14 on 2024-07-16 13:19

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversationmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.get_upload_conversation_message_file_path),
        ),
    ]
