# Generated by Django 4.2.11 on 2024-03-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
