# Generated by Django 4.2.14 on 2024-07-16 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_oauth2_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_oauth2_picture',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_picture', to=settings.AUTH_USER_MODEL),
        ),
    ]
