# Generated by Django 4.2.14 on 2024-07-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='tags',
            field=models.ManyToManyField(related_name='announcements', to='announcement.tag'),
        ),
    ]
