# Generated by Django 4.2.11 on 2024-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor_avg_rating_tutorscheduleitems_tutorratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
