# Generated by Django 4.2.11 on 2024-03-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_tutor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorscheduleitems',
            name='description',
        ),
    ]
