# Generated by Django 4.2.11 on 2024-03-30 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0005_remove_tutorscheduleitems_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorratings',
            name='rating',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='tutorratings',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
