# Generated by Django 4.2.11 on 2024-04-01 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0006_alter_tutorratings_rating_alter_tutorratings_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorratings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutorratings',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorratings',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_ratings', to='tutor.tutor'),
        ),
    ]
