# Generated by Django 4.2.11 on 2024-04-01 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0007_alter_tutorratings_id_alter_tutorratings_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorratings',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorratings',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_ratings', to='tutor.tutor'),
        ),
    ]
