# Generated by Django 4.2.11 on 2024-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_alter_tutorratings_student_alter_tutorratings_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='price',
            field=models.SmallIntegerField(default=0),
        ),
    ]
