# Generated by Django 4.2.11 on 2024-04-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_tutor_in_person_sessions_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tutoring_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
