# Generated by Django 4.2.11 on 2024-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_tutor_tutoring_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='group_sessions_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='individual_sessions_available',
            field=models.BooleanField(default=False),
        ),
    ]
