# Generated by Django 4.2.11 on 2024-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_tutor_group_sessions_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutoring_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
