# Generated by Django 4.2.14 on 2024-07-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_alter_tutor_tutoring_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutoring_location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
