# Generated by Django 4.2.14 on 2024-08-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatnotification',
            name='user_notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notification', to='notification.usernotification'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
