# Generated by Django 4.2.14 on 2024-07-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_users_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
    ]
