# Generated by Django 4.2.14 on 2024-08-01 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_userchatnotification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatnotification',
            name='user_notification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_notification', to='notification.usernotification'),
        ),
    ]
