# Generated by Django 4.2.14 on 2024-07-25 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_tutorscheduleitems_is_reserved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_alter_tutoringreservation_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutoringreservation',
            unique_together={('user', 'schedule_item')},
        ),
    ]
