# Generated by Django 4.2.14 on 2024-07-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_tutoringreservation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutoringreservation',
            unique_together=set(),
        ),
    ]
