# Generated by Django 4.2.14 on 2024-07-25 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_tutorscheduleitems_is_reserved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0004_alter_tutoringreservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringreservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='tutoringreservation',
            unique_together={('user', 'schedule_item')},
        ),
    ]
