# Generated by Django 4.2.13 on 2024-07-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_respond_responder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respond',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responds', to='reporting.issue'),
        ),
    ]
