# Generated by Django 4.2.14 on 2024-08-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_issue_category_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('violation', 'Naruszenie regulaminu'), ('technical_issue', 'Problem techniczny'), ('help_request', 'Prośba o pomoc')], max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('in_progress', 'W trakcie'), ('resolved', 'Rozwiązane'), ('closed', 'Zamknięte')], default='new', max_length=20),
        ),
    ]
