on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull_and_test:
    name: Run Pull and Test Django App in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from GitHub Secrets
        run: |
          echo "DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}" >> .env
          echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> .env
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "DB_ENGINE=${{ secrets.DB_ENGINE }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "AUTH_COOKIE_SECURE=${{ secrets.AUTH_COOKIE_SECURE }}" >> .env
          echo "REDIRECT_URLS=${{ secrets.REDIRECT_URLS }}" >> .env
          echo "GOOGLE_AUTH_KEY=${{ secrets.GOOGLE_AUTH_KEY }}" >> .env
          echo "GOOGLE_AUTH_SECRET_KEY=${{ secrets.GOOGLE_AUTH_SECRET_KEY }}" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> .env

      - name: Build Docker images
        run: |
          docker compose build

      - name: Run Tests in Docker
        run: |
          docker compose up -d  
          docker compose exec bdio-app python manage.py test

      - name: Clean up Docker containers, networks, and volumes
        run: |
          docker compose down --volumes --remove-orphans  # Remove volumes and orphaned containers
